# fly.toml app configuration file generated for siderolls-web on 2024-07-01T20:48:36-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'siderolls-web'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
